// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int64
	Email     sql.NullString
	Username  sql.NullString
	PwHash    sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}
