// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package user

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, pw_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, pw_hash, created_at, updated_at
`

type CreateUserParams struct {
	Username sql.NullString
	Email    sql.NullString
	PwHash   sql.NullString
}

type CreateUserRow struct {
	ID        int64
	Username  sql.NullString
	Email     sql.NullString
	PwHash    sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Email, arg.PwHash)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PwHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, pw_hash, created_at, updated_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID        int64
	Username  sql.NullString
	Email     sql.NullString
	PwHash    sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByUsername(ctx context.Context, username sql.NullString) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PwHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
